@TodoApi_HostAddress = http://localhost:5151

GET {{TodoApi_HostAddress}}/api/TodoItems HTTP/1.1
Accept: application/json


### 

POST {{TodoApi_HostAddress}}/api/TodoItems HTTP/1.1
Content-Type: application/json

{
  "isComplete": true,
  "name": "Buy more tissues"
}
